name: parser compilation

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  compilation_tests:
    runs-on: ubuntu-latest
    strategy:
      #max-parallel: 10
      matrix:
        cc: [gcc, clang, g++, clang++]
        optflags: ["-O3", "-O2", "-O1"]
    steps:
      # Checkout repository
      - name: checkout repository
        uses: actions/checkout@v2
      # Run actions
      # parser compilation tests
      - name: parser tests
        env:
          CC: ${{ matrix.cc }}
          EXTRA_CFLAGS: ${{ matrix.optflags }}
        shell: bash
        run: |
          # Compilation tests of all cases
          #
          make
        continue-on-error: false
